### ISSUE TITLE
8 No such module '

### ISSUE THREAD

**Issue by dawoodazhar** [ladmini/LZViewPager#40] opened 2024-04-26 16:40 UTC
8 No such module 'SnapKit'
Missing package product 'SnapKit'

**Comment by PawanRamteke** [comment] 2024-05-03 08:16
try below command before run the demo project.

carthage update --cache-builds --use-xcframeworks --platform ios

**Comment by ladmini** [comment] 2024-07-08 07:28
maybe duplicate of #41

**Closed as completed by ladmini** 2024-07-08 07:28 UTC
