### ISSUE TITLE
Snapkit with LzViewPager

### ISSUE THREAD

**Issue by AsimSafarli** [ladmini/LZViewPager#39] opened 2024-04-15 01:31 UTC
8 No such module 'SnapKit'
Missing package product 'SnapKit'

**Comment by ladmini** [comment] 2024-04-15 03:14
Which methods did you install LZViewPager?  
CocoaPods or Carthage? If CocoaPods, have you try 
```bash
pod repo update
```
before
```bash
pod install
```

**Comment by AsimSafarli** [comment] 2024-04-15 23:20
i  have already use cocapods but i don't completed this error by the way I change my way . i  have use swift UI

**Comment by ladmini** [comment] 2024-07-08 07:29
maybe duplicate of #41

**Closed as completed** 2024-07-08 07:29 UTC
